replicaCount: 1
image:
  repository: "ghcr.io/treestack/geocoder"
  pullPolicy: IfNotPresent
  tag: "master"

application:
  port: 5353

workingDirectory: .

environment:
  - name: GEOCODER_LOGLEVEL
    value: "INFO"
  - name: GEOCODER_BIND_ADDRESS
    value: "0.0.0.0:5353"
  - name: GEOCODER_DATA_FILE
    value: "./cities.txt"
  - name: GEOCODER_WATCH_FOR_CHANGES
    value: "true"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

service:
  type: LoadBalancer
  port: 5353

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 10

nodeSelector: {}

tolerations: []

affinity: {}
